export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

//user Register
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//user Login
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

//add to cart
export const ADD_TOCART_BEGIN = "ADD_TOCART_BEGIN";
export const ADD_TOCART_SUCCESS = "ADD_TOCART_SUCCESS";
export const ADD_TOCART_ERROR = "ADD_TOCART_ERROR";

//get cart
export const GET_CART_BEGIN = "GET_CART_BEGIN";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

//get call products
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

//delete cart item
export const DELETE_TOCART_BEGIN = "DELETE_TOCART_BEGIN";
export const DELETE_TOCART_SUCCESS = "DELETE_TOCART_SUCCESS";
export const DELETE_TOCART_ERROR = "DELETE_TOCART_ERROR";
